version: '3.1'
services:
  stats-server:
    build: ./stat-service/server
    image: stat-service
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stats-db

    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmdb:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SERVICES_STATSSERVICE_URI=http://stat-server:9090

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm